# Config file for DeepForest pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 4
gpus: 1
distributed_backend:
batch_size: 1

#Non-max supression of overlapping predictions
nms_thresh: 0.05
score_thresh: 0.1

train:

    csv_file: /datadrive/Data/train_subset.csv
    root_dir: /datadrive/Data/train
    
    #Optomizer  initial learning rate
    lr: 0.001

    #Print loss every n epochs
    epochs: 50
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False
    #pin images to GPU memory for fast training. This depends on GPU size and number of images.
    preload_images: False
    
validation:
    #callback args
    csv_file: /datadrive/Data/val_filter4.csv
    root_dir: /datadrive/Data/val
    #Intersection over union evaluation
    iou_threshold: 0.4
    val_accuracy_interval: 1