####
# Creator: Rowan Converse (rowanconverse@unm.edu)
# Date: 2022/08/02
# Purpose: Translate raw labels generated by USFWS biologists in Labebox into COCO format for public release 
# Ref COCO Camera Trap Standard: https://cocodataset.org/#format-data
####

#Load necessary modules
import json
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime
from collections import OrderedDict 

#Load data
zooniverse = pd.read_csv('Data/zooniverse_snippet.csv')

###Info 
whattimeisitrightnowdotcom = datetime.date.today()
year = {"year": 2022}
vers = {"version": "1.0"}
desc = {"description": "This dataset includes annotations of UAS imagery collected x to y , 2018, at Bosque del Apache National Wildlife Refuge in New Mexico. Over 3,000 volunteers identified waterfowl in 611 images using three morphological categories (Duck, Goose, Crane). The labels were collected via the participatory science platform, Zooniverse. Contact Rowan Converse (rowanconverse@unm.edu) with questions about this dataset. Please cite using a CC-By license with ASPIRE as the data repository."}
contr = {"contributor": "Center for the Advancement of Spatial Informatics Research and Education (ASPIRE), University of New Mexico; Project Manager Rowan Converse"}
url = {"url": "https://aspire.unm.edu/projects/project/ducks-and-drones.html"}
date = {"date created": whattimeisitrightnowdotcom}

infolist = [year, vers, desc, contr, url, date]

info = {"info": infolist}

###Images

for i in range(len(zooniverse)):
  #info: define version, description. Optional: year, contributor, date created
  version = 1.0
  description = "This dataset includes annotations of UAS imagery collected x to y , 2018, at Bosque del Apache National Wildlife Refuge in New Mexico. Fifteen biologists from the US Fish and Wildlife Service identified waterfowl in thirteen benchmark images to the species level. Contact Rowan Converse (rowanconverse@unm.edu) with questions about this dataset. Please cite using a CC-By license with ASPIRE as the data repository."
  #images: use code for image list. Need to create unique ID, file name. Can add other info
  images = zooniverse.subject_ids
  #categories: use code for species list (name), match with integer values (id) (NOT ZERO)

  #Annotations: import ID, Image ID, Category ID, bounding boxes (x,y, width, height). 
 
  #also add labeler info
  users = data.user_id