####
# Creator: Rowan Converse (rowanconverse@unm.edu), with edits from Hays Barrett and Tyler Eschelman 
# Date: 2023/03/03
# Purpose: Translate raw labels generated by USFWS biologists in Labebox into COCO format for public release 
# Ref COCO Camera Trap Standard: https://cocodataset.org/#format-data
####
#Load necessary modules
import json
from UliEngineering.Math.Coordinates import BoundingBox
import numpy as np
import pandas as pd

#Load JSON file of Labelbox labels
path = r"/Users/rowanconverse/Library/CloudStorage/OneDrive-UniversityofNewMexico/CV4Ecology/Prototyping/Data/Labels/originals/labelbox.json"
with open(path) as f:
  usfws = json.load(f)

annos = []
#We iterate over each label event one at a time.
for label_event in usfws:
    #skip if the user skipped
    if label_event["Skipped"]==False:
        #for each bird that the user labeled iterate over each label geom that the user created.
        for bird in label_event['Label']:
            for geom_obj in label_event['Label'][bird]:
                #add the points to a 2 dimensional array
                polycoords = [[point['x'],point['y']] for point in geom_obj['geometry']]
                #Convert to a numpy array
                polycoords=np.array(polycoords)
                #Create a traditional bounding box
                minbox=BoundingBox(polycoords)
                #Convert bbox to COCO bbox format
                bbox = [minbox.minx, minbox.miny, minbox.width, minbox.height]
                #Create annotation and add to annos array.
                annotation = {
                "annotation_ID": len(annos)+1,
                "bbox": list(bbox),
                "filename": label_event["External ID"],
                "labeler": label_event["Created By"],
                "category": bird
                }
                annos.append(annotation)

df = pd.DataFrame(annos)
df.to_csv('labelbox.csv')